FEC-11914 Bookmarks are not sent when the ks is set on the media options alone.
kaltura/kaltura-player-ios pull request #49
Opened 2022-01-25 02:14 UTC by x-NR-x

Update to Phoenix Analytics was not performed when the ks was set in the media, therefore bookmarks where not being sent.
Added code to not override Phoenix Analytics config if it was set in the player options upon init.
The pluginConfig was not sent, therefore update to Phoenix Analytics was not called.

2022-01-25 13:36 UTC, chausov commented on Sources/OTT/KalturaOTTPlayer.swift
> +        let playerKSNotSet = playerOptions.ks?.isEmpty ?? true
```suggestion
var playerKSAvailable = false
var mediaKSAvailable = false

if let playerKs = playerOptions.ks {
    playerKSAvailable = !playerKs.isEmpty
}

if let mediaKs = mediaOptions?.ks {
    mediaKSAvailable = !mediaKs.isEmpty
}

// In cases player KS is NOT available we still may update Phoenix Analytics if media KS is available.
let shouldUpdatePhoenixAnalytics = !playerKSAvailable && mediaKSAvailable
```

2022-01-27 17:18 UTC, x-NR-x commented on Sources/OTT/KalturaOTTPlayer.swift
> +        let playerKSNotSet = playerOptions.ks?.isEmpty ?? true
Was changed

2022-01-29 19:26 UTC, chausov requested changes

2022-01-29 19:26 UTC, chausov commented on Sources/Playlist/KPPlaylistController.swift
> +                    self.entries[entryIndex] = mediaEntry
What are the benefits of changing whole entry and not only sources?

2022-01-31 15:06 UTC, x-NR-x commented on Sources/Playlist/KPPlaylistController.swift
> +                    self.entries[entryIndex] = mediaEntry
We need other values as well and not just the sources.

2022-02-01 10:31 UTC, chausov approved these changes

2022-02-01 12:00 UTC, merged