FEC-10909 FEC-12435 Ads progress indicator/seekbar fixes
kaltura/kaltura-player-ios pull request #73
Opened 2022-08-11 11:10 UTC by chausov

Solves:
FEC-10909 progress indication added for ads
FEC-12435 seeking disabled while ads are playing

2022-08-16 13:50 UTC, x-NR-x requested changes

2022-08-16 13:50 UTC, x-NR-x commented on Sources/UI/KPMediaPlayer.swift
> +    private func handleAdEvents() {
Why was this separated? The adStarted and adComplete events are already in the registerAdEvents function.
And please use the type alias KPAdEvent and not the Playkit AdEvent.

2022-08-17 15:12 UTC, x-NR-x commented on Sources/UI/KPMediaPlayer.swift
> +                    self.mediaProgressSlider.maximumTrackTintColor = UIColor.lightGray.withAlphaComponent(0.5)
I think this needs to be in ad skipped as well.

2022-08-24 10:05 UTC, x-NR-x requested changes
Please fix:
- The duration label is not updated back to the media value after the ad (pre/mid).
- The 'mediaProgressSlider.bufferValue' should not be shown upon an ad, but should be seen after the ad.

2022-08-24 15:04 UTC, chausov commented
> Please fix:
> 
> * The duration label is not updated back to the media value after the ad (pre/mid).
> * The 'mediaProgressSlider.bufferValue' should not be shown upon an ad, but should be seen after the ad.

Fixed

2022-08-30 10:12 UTC, x-NR-x approved these changes

2022-08-30 11:25 UTC, merged